### PR TITLE
Only check suported shells

### PR DESCRIPTION
**Pull request by mendess**

### CODE REVIEW

**Comment by Azbagheri** [comment]
Hey @mendess, can you please let us know a bit more about the issue you are trying to fix with these changes? 
In general, Shell Linter is a wrapper around Shellcheck and we are avoiding changing the original behavior of Shellcheck. If one of our users unknowingly tries to lint an unsupported script, we would rather show them the Shellcheck error than exclude their script from linting. With that said, we are offering the `path` parameter in our action to enable our users to control the scripts they want to lint using Shell Linter.

**Comment by mendess** [comment]
My intention is to lint my dotfiles which are a mix of scripts in many languages, so the `path` variable just isn't enough for me.

I also figured this might be an issue in a large project where many files in different languages but all containing shebangs are present. 

I also don't think this changes the behaviour of shellcheck, you already don't check files without a shebang so I think only checking files with supported shebangs is the next logical step.

**Comment by btilford** [comment]
Running into this same issue I've got a `./bin` directory in a repo that is mostly bash scripts but there is occasionally a .js or other nons shell like script there as well. It's in `./bin` because that gets added to the PATH so having to change the PATH a bunch isn't really ideal.

**Comment by asadmansr** [comment]
Hey @mendess, thank you for opening the PR. Unfortunately, we're unable to merge these changes at the moment. The changes to the action.yml will actually change the action's name on marketplace, which we do not want. We have addressed the supported shell through a different implementation along with other bug fixes and improvements, that are already released in v0.5.0. To apply these changes to your github action workflow, you can now reference:
```
uses: azohra/shell-linter@v0.5.0

# or opt-in to the latest version
uses: azohra/shell-linter@latest
```

@btilford the shell-linter action deploys two-set of checks when linting a file. It first checks the file extension (.sh file) followed by the shebang.

Feel free to open an issue or feature request, and we'll be happy to look into it. Closing this PR as of now. Thank you.

**Pull request closed without merging**
